#   ansible/inventory.yml

[routers]
r1 ansible_host=clab-ccna-lab-r1 ansible_connection=docker
r2 ansible_host=clab-ccna-lab-r2 ansible_connection=docker

[hosts]
host1 ansible_host=clab-ccna-lab-host1 ansible_connection=docker
host2 ansible_host=clab-ccna-lab-host2 ansible_connection=docker